### ISSUE TITLE
Hivemind-CLI not available in hivemind-cli container

### ISSUE THREAD

**Issue by j1nx** [JarbasHiveMind/hivemind-docker#1]
Used the ovos-installer to install the hivemind docker images. A hivemins-cli container is pulled however the command itself is not available within the containers?

pip list does not show the packages that should be installed according the requirements.txt file within the cli folder.

It does however have a "jarbas-hive-mind" 0.10.7 package installed.
Mannually installing the two packages from that txt file results in;
```
Successfully installed HiveMind-cli-0.5.0a2 HiveMind_presence-0.0.2a4 PGPy-0.6.0 bitarray-2.9.2 bitstring-4.2.2 hivemind_bus_client-0.0.4a22 poorman-handshake-0.2.2a3

Successfully installed hivemind-ggwave-0.0.1 jarbas-hive-mind-0.13.1a14 tornado-6.4
```

Resulting in;
```
ovos@hivemind_cli:~$ pip list | grep Hive
HiveMind-cli              0.5.0a2
HiveMind-presence         0.0.2a4
ovos@hivemind_cli:~$ pip list | grep hive
hivemind-bus-client       0.0.4a22
hivemind-ggwave           0.0.1
jarbas-hive-mind          0.13.1a14
```

hivemind-cli is then available (no capitals, so the readme of that repo also needs changes)

**Comment by goldyfruit** [comment]
Just rebuild the image, should be fine now.
